{{ $_ := set . "Values" ( include "spire-server.profile-values" . | fromYaml ) }}
{{- if eq (.Values.controllerManager.enabled | toString) "true" }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "spire-controller-manager.fullname" . }}-webhook
webhooks:
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "spire-controller-manager.fullname" . }}-webhook
        namespace: {{ include "spire-server.namespace" . }}
        path: /validate-spire-spiffe-io-v1alpha1-clusterfederatedtrustdomain
    failurePolicy: {{ .Values.controllerManager.validatingWebhookConfiguration.failurePolicy }}
    name: vclusterfederatedtrustdomain.kb.io
    rules:
      - apiGroups: ["spire.spiffe.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["clusterfederatedtrustdomains"]
    sideEffects: None
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "spire-controller-manager.fullname" . }}-webhook
        namespace: {{ include "spire-server.namespace" . }}
        path: /validate-spire-spiffe-io-v1alpha1-clusterspiffeid
    failurePolicy: {{ .Values.controllerManager.validatingWebhookConfiguration.failurePolicy }}
    name: vclusterspiffeid.kb.io
    rules:
      - apiGroups: ["spire.spiffe.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["clusterspiffeids"]
    sideEffects: None
{{- end }}
