{{- if eq (.Values.tornjak.enabled | toString) "true" }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "spire-server.namespace" . }}
  name: {{ include "spire-tornjak.servicename" . }}
  {{- with .Values.tornjak.config.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    {{- include "spire-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tornjak.config.service.type }}
  selector:
   {{- include "spire-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ include "spire-tornjak.portname" . }}
      port: {{ .Values.tornjak.config.service.port }}
      targetPort: {{ include "spire-tornjak.portname" . }}
      protocol: TCP
{{- end }}
